### ISSUE TITLE
Batch minting for unique pieces

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/minter-sdk#125]
Hello team,

We are actively looking for a way to mint 10000 unique NFT's. For now we have to mint them 1 by 1. We've been following the open minter project and this feature has been pushed back since v0.4

Are you still working on a way to do it, or have you given up on this feature ?

Seems interesting for large collection projects similar to crypto punks, hashmasks for example.

Thanks for the reply

**Comment by EGuenz** [comment]
Hi [Editions](https://github.com/tqtezos/minter-sdk/tree/main/packages/minter-contracts/ligo/src/minter_collection/editions) lets you "mint" 1000 editions of a unique NFT. (Here)[https://github.com/tqtezos/minter/issues/318] is the issue in the Minter repo to track the progress of the integration of this contract with open minter

I suggest inquiring under that issue for more info regarding that timeline. 

Thanks and let me know if that answered your question!

**Comment by paulo60pg** [comment]
That is not what I'm looking for. I'm looking for a way to mint a batch of 10000 different pieces. Every piece is different and exists in 1/1 edition. Basically I would like to mint 10000 unique 1/1 pieces. Like crypto punks or hashmask, each one of the 10 000 is different.

**Comment by EGuenz** [comment]
We have plans to support minting that many NFTs that we will begin working on in May. Batch minting is possible at the moment for a smaller number of unique NFTs however, just not that many.

**Comment by paulo60pg** [comment]
How many can we mint and how to do it ? I don't see it in the minter.
If we could mint them 10 by 10 it would be already great !

**Comment by EGuenz** [comment]
This feature is not yet integrated with minter. You can open an issue in that repo to follow up.

You can use this contract: https://github.com/tqtezos/minter-sdk/blob/main/packages/minter-contracts/bin/fa2_multi_nft_asset.tz for example with the tezos-client https://tezos.gitlab.io/introduction/howtouse.html#client to batch mint. 

How many you can mint is limited largely by how much token metadata is included for each token. I haven't heavily tested the limits of batch minting using this contract but I would estimate with minimal token metadata you should be able to batch mint at max a few hundred.

**Comment by paulo60pg** [comment]
Thank you so much, that would be perfect !  I have created https://github.com/tqtezos/minter/issues/269 and it seems other people want this. There is also https://github.com/tqtezos/minter/issues/164 that was open and almost implemented, but then pushed back to v2 then v3 then v4. Any chance to see this implemented in the minter soon ?
