### ISSUE TITLE
Fix intermittent test failure in `test/auction/fa2-auction-fee.test.ts`

### ISSUE THREAD

**Issue by zachrbrown** [tqtezos/minter-sdk#137]
`fa2-auction-fee.test.ts` reliably passes locally, yet reliably fails in CI. @EGuenz believes this is due to the combination of the inherent time sensitivity of the test and its execution on a slower machine (the CI runner node in the failure case).

We should tweak whatever time constants are at play to ensure the test reliably succeeds in CI.

**Comment by zachrbrown** [comment]
Reopening. Still seeing this happen occasionally, though much less frequently.

**Comment by EGuenz** [comment]
I have not been seeing it anymore after some tweaks so I will close.
