### ISSUE TITLE
Issue in package installation. 

### ISSUE THREAD

**Issue by ghulammurtaza** [tqtezos/minter-sdk#178]
I am trying to run below command for openminter on my local machine and getting error

`npm i @tqtezos/minter-contracts`

no such file or directory, chmod ‘/node_modules/@tqtezos/minter-contracts/env TZ_NETWORK=sandbox ts-node src/bootstrap-contracts-config.ts’

when I run it through yar it works fine but then yarn compile-ligo doesn’t work.

`yarn add @tqtezos/minter-contracts`

<img width="885" alt="Screenshot 2021-06-16 at 10 17 00 AM" src="https://user-images.githubusercontent.com/1614410/122172832-9c730080-ce9a-11eb-8a1e-713958972017.png">

stack: 
mac os
npm 7.17.0
node v14.15.1

**Comment by zachrbrown** [comment]
Hi there. We discovered a couples issues with the `package.json` file which were causing the issues you were reporting when installing with `npm`. They have been addressed in `1.6.1`. Can you try with the most recent version?

**Comment by ghulammurtaza** [comment]
it is not working with yarn or npm. ts-jest@26.1.3 is not compatible with ts version 4.1.5.  Please see screen shot. 
<img width="778" alt="Screenshot 2021-06-17 at 4 56 29 PM" src="https://user-images.githubusercontent.com/1614410/122400840-86963600-cf95-11eb-8505-915d3fd3ce64.png">

I can use yarn but above dependency issue is same for both.

**Comment by ghulammurtaza** [comment]
same error with yarn. Please see attachment. 
<img width="893" alt="Screenshot 2021-06-17 at 6 10 44 PM" src="https://user-images.githubusercontent.com/1614410/122403106-86973580-cf97-11eb-9604-f4b1b8fc684e.png">

**Comment by zachrbrown** [comment]
This is odd. The `minter-contracts` doesn't have any runtime dependencies (only development dependencies). Are you trying to install with dev dependencies by chance? Perhaps you could give me more context as to how I can reproduce this. I can install without issue in a fresh project using both `npm` and `yarn`.

```
npm i @tqtezos/minter-contracts                                                                                                                       ✔  10154  13:17:57

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
```
```
yarn add @tqtezos/minter-contracts                                                                                                                    ✔  10156  13:19:07
yarn add v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @tqtezos/minter-contracts@1.6.1
info All dependencies
└─ @tqtezos/minter-contracts@1.6.1
✨  Done in 1.00s.
```

**Comment by ghulammurtaza** [comment]
can we have chat over slack or telegram to fix this issue please? I want to move on and stuck with this SDK think.

**Comment by zachrbrown** [comment]
Sure. i'm in the `tezos-dev` channel `@Zach Brown`. Feel free to message me there.
