### ISSUE TITLE
Suggestion: yarn.lock XOR package-lock.json

### ISSUE THREAD

**Issue by d4hines** [tqtezos/minter-sdk#52]
This is a nitpick, but it could save you or an unfortunate user quite a bit of headache down the road: I suggest using either yarn or npm to manage deps, but not both, and, in particular, don't commit both yarn.lock and package-lock.json. They aren't always compatible, and weird things can happen, especially if you switch between the two.

**Comment by zachrbrown** [comment]
Closed via #59
