### ISSUE TITLE
Ensure admin tests can be run without user having to manually execute other scripts

### ISSUE THREAD

**Issue by zachrbrown** [tqtezos/minter-sdk#64]
Tests that interact with admin users require an admin user to be provisioned in the sandbox environment to execute successfully. We should automate this process such that tests don't require explicit user setup to execute correctly.

Via @emishur: 
We can do two things:
- Modify existing flextesa image and bootstrap many test accounts. So, it gets maintained with any flextesa updates
- Bootstrap those accounts ourselves when starting the sandbox using taquito

**Comment by EGuenz** [comment]
This was closed by #112. An admin account by the name of Eve is bootstrapped when starting the sandbox, but it is passed directly to the flextesa Edobox image as a command line argument. There is no interaction with Taquito.
